### ISSUE TITLE
child tag specification

### ISSUE THREAD

**Issue by aguilera51284** [arccoza/postcss-aspect-ratio#1]
I need to provide for the child tag.  it is for more modularity.

**Comment by arccoza** [comment]
I'm not sure what you're asking, perhaps you can explain further with some html?

**Comment by aguilera51284** [comment]
it would be something like this
```css
/* Input. */
.aspect-box {
  position: relative;
  background: lime;
  aspect-ratio: '16:9' 'image';
}

/* Output. */
.aspect-box {
  position: relative;
  background: lime;
  box-sizing: border-box;
}

.aspect-box > image {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0; 
  left: 0; 
  box-sizing: border-box;
}

.aspect-box:before{
  position: relative;
  display: block;
  content: "";
  padding-top: 56.25%;
  box-sizing: border-box;
}
```

**Comment by arccoza** [comment]
```css
/* Input. */
.aspect-box {
  position: relative;
  background: lime;
  aspect-ratio: '16:9';
}

/* Output. */
.aspect-box {
  position: relative;
  background: lime;
  box-sizing: border-box;
}

 /*This selector targets any immediate child, it should work for any situation.*/
.aspect-box > * {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0; 
  left: 0; 
  box-sizing: border-box;
}

.aspect-box:before{
  position: relative;
  display: block;
  content: "";
  padding-top: 56.25%;
  box-sizing: border-box;
}
```

You could have any element in the `.aspect-box`, the `> *` selector will select any child, so you could have:

```html
<div class="aspect-box">
  <img src="">
</div>
```

I see no advantage to having a second argument to specify the child selector.
