### ISSUE TITLE
not calculating aspect ratio

### ISSUE THREAD

**Issue by dbox** [arccoza/postcss-aspect-ratio#2]
Can you tell me what I may be doing wrong:

``` css
.beans {
  border: 5px solid green;
  aspect-ratio: '16/9';
  background: blue;
}
```

output:
![image](https://cloud.githubusercontent.com/assets/296130/15863364/b9d871c4-2ca0-11e6-9fdb-8a20131282dc.png)
