### ISSUE TITLE
Avoid absolutely positioning children

### ISSUE THREAD

**Issue by madeleineostoja** [arccoza/postcss-aspect-ratio#6]
By using the pseudo element as a dummy sizing element within the flow of the document (and clearing floats with another pseudo element) you can avoid absolutely positioning children. This has a few advantages:

1) Overflowing content expands the box vertically, instead of just getting clipped

2) Children can be positioned as you want, rather than needing to be absolute

It could look something like this

```css
.foo::before {
  content: "";
  width: 1px;
  margin-left: -1px;
  float: left;
  padding-top: 56.25%;
}

.foo::after {
  content: "";
  display: table;
  clear: both;
}
```
